### ISSUE TITLE
Support user shutdown request: SIGTERM

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/deepocli#23]
Sometimes we want to abort the current execution, and with the `deepomatic-rpc` backend it cannot be interrupted: ctrl-c (SIGTERM) does nothing (is it stuck waiting on a reply on the rabbitmq reply queue?)

**Comment by maingoh** [comment]
I think we can close now ? It handles keyboardinterrupt

**Comment by thomas-riccardi** [comment]
In the currently published version there is indeed some keyboardinterrupt handling:
Tested with RPC:
- 1 SIGTERM: `Stop asked, waiting for threads to process queued messages.`: then after ~15s: it exits with `deepomatic.rpc.amqp.exceptions.Timeout: An AMQP timeout occured after 60 seconds`
This is really strange: we didn't wait 60s; and the output is really *not* user friendly:
```
root@27338fc28a83:/# deepo infer -r 709 -i kitty-551554__340.jpg -o out.json -u amqp://some-rabbit -k foobar
[INFO deepomatic.cli.input_data 2019-05-27 09:51:09,475 44 140686483289856 common.py:28] Input processing:   0%|          | 0/1 [00:00<?, ?it/s]
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,477 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,477 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,499 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,508 44 140686483289856 client.py:284] Declared <Queue foobar -> <Exchange v0.3.direct(direct) bound to chan:2> -> foobar bound to chan:2>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,511 44 140686483289856 client.py:284] Declared <Queue tmp.048b0583-c68d-4bbc-80f8-13b3fc7dca27 -> <Exchange v0.3.direct(direct) bound to chan:2> -> tmp.048b0583-c68d-4bbc-80f8-13b3fc7dca27 bound to chan:2>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,515 44 140686483289856 client.py:284] Declared <LRUConsumer: [<Queue tmp.048b0583-c68d-4bbc-80f8-13b3fc7dca27 -> <Exchange v0.3.direct(direct) bound to chan:2> -> tmp.048b0583-c68d-4bbc-80f8-13b3fc7dca27 bound to chan:2>]>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,516 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,517 44 140685411874560 thread_base.py:180] Quitting InputThread_0
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,517 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,532 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,533 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,533 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,544 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,544 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,545 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,556 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,556 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,556 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,570 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,571 44 140686483289856 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,571 44 140686483289856 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:09,583 44 140686483289856 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,686 44 140685403481856 thread_base.py:180] Quitting PrepareInferenceThread_0
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,739 44 140686483289856 thread_base.py:180] Quitting SendInferenceGreenlet_0
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,790 44 140686483289856 thread_base.py:180] Quitting SendInferenceGreenlet_1
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,840 44 140686483289856 thread_base.py:180] Quitting SendInferenceGreenlet_2
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,891 44 140686483289856 thread_base.py:180] Quitting SendInferenceGreenlet_3
[INFO deepomatic.cli.thread_base 2019-05-27 09:51:09,943 44 140686483289856 thread_base.py:180] Quitting SendInferenceGreenlet_4
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:51:39,480 44 140686483289856 client.py:127] Sending heartbeat
^C[INFO deepomatic.cli.thread_base 2019-05-27 09:51:42,729 44 140686483289856 thread_base.py:270] Stop asked, waiting for threads to process queued messages.
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:09,483 44 140686483289856 client.py:127] Sending heartbeat
[ERROR deepomatic.cli.thread_base 2019-05-27 09:52:09,585 44 140686483289856 thread_base.py:73] list.remove(x): x not in list
[ERROR deepomatic.cli.thread_base 2019-05-27 09:52:09,587 44 140686483289856 thread_base.py:172] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/workflow/rpc_workflow.py", line 37, in get_predictions
    response = self._consumer.get(self._correlation_id, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/rpc/amqp/entities.py", line 282, in get
    raise Timeout(timeout)
deepomatic.rpc.amqp.exceptions.Timeout: An AMQP timeout occured after 60 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/cmds/infer.py", line 177, in process_msg
    predictions = frame.inference_async_result.get_predictions(timeout=60)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/workflow/rpc_workflow.py", line 45, in get_predictions
    raise InferenceTimeout(timeout)
deepomatic.cli.workflow.workflow_abstraction.InferenceTimeout: timeout reached after 60

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/thread_base.py", line 170, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/thread_base.py", line 159, in _run
    msg_out = self.process_msg(msg_in)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/cmds/infer.py", line 196, in process_msg
    LOGGER.error("Couldn't get predictions for the whole batch in enough time ({} seconds). Ignoring frames {}.".format(e.timeout, self.batch))
AttributeError: 'ResultInferenceGreenlet' object has no attribute 'batch'

[INFO deepomatic.cli.thread_base 2019-05-27 09:52:09,587 44 140686483289856 thread_base.py:180] Quitting ResultInferenceGreenlet_0
[INFO deepomatic.cli.output_data 2019-05-27 09:52:09,639 44 140685395089152 output_data.py:26] Writing out.json ..
[INFO deepomatic.cli.output_data 2019-05-27 09:52:09,639 44 140685395089152 output_data.py:28] Writing out.json done
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:09,640 44 140685395089152 thread_base.py:180] Quitting OutputThread_0
```

- 2 SIGTERM: 
  - first SIGTERM: `Stop asked, waiting for threads to process queued messages.`
  - second SIGTERM: `Hard stop`, but it pauses, still waiting for the previously mentioned AMQP timeout:
```
root@27338fc28a83:/# deepo infer -r 709 -i kitty-551554__340.jpg -o out.json -u amqp://some-rabbit -k foobar
[INFO deepomatic.cli.input_data 2019-05-27 09:52:16,963 67 140275327649536 common.py:28] Input processing:   0%|          | 0/1 [00:00<?, ?it/s]
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,964 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,964 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,977 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,978 67 140275327649536 client.py:284] Declared <Queue foobar -> <Exchange v0.3.direct(direct) bound to chan:2> -> foobar bound to chan:2>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,981 67 140275327649536 client.py:284] Declared <Queue tmp.39998377-d43b-4b3f-9f83-cb4296580649 -> <Exchange v0.3.direct(direct) bound to chan:2> -> tmp.39998377-d43b-4b3f-9f83-cb4296580649 bound to chan:2>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,985 67 140275327649536 client.py:284] Declared <LRUConsumer: [<Queue tmp.39998377-d43b-4b3f-9f83-cb4296580649 -> <Exchange v0.3.direct(direct) bound to chan:2> -> tmp.39998377-d43b-4b3f-9f83-cb4296580649 bound to chan:2>]>
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,986 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:16,986 67 140274324616960 thread_base.py:180] Quitting InputThread_0
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:16,986 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,000 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,001 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,001 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,018 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,018 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,018 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,034 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,034 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,035 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,048 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,048 67 140275327649536 client.py:263] New connection to amqp://guest:**@some-rabbit:5672//
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,048 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:17,058 67 140275327649536 client.py:284] Declared Exchange v0.3.direct(direct)
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,161 67 140274316224256 thread_base.py:180] Quitting PrepareInferenceThread_0
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,214 67 140275327649536 thread_base.py:180] Quitting SendInferenceGreenlet_0
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,266 67 140275327649536 thread_base.py:180] Quitting SendInferenceGreenlet_1
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,317 67 140275327649536 thread_base.py:180] Quitting SendInferenceGreenlet_2
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,368 67 140275327649536 thread_base.py:180] Quitting SendInferenceGreenlet_3
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:17,418 67 140275327649536 thread_base.py:180] Quitting SendInferenceGreenlet_4
^C[INFO deepomatic.cli.thread_base 2019-05-27 09:52:19,270 67 140275327649536 thread_base.py:270] Stop asked, waiting for threads to process queued messages.
^C[INFO deepomatic.cli.thread_base 2019-05-27 09:52:19,974 67 140275327649536 thread_base.py:274] Hard stop
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:19,974 67 140275327649536 thread_base.py:248] Purging queues
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:19,974 67 140275327649536 thread_base.py:254] Purging queues done
[INFO deepomatic.cli.output_data 2019-05-27 09:52:19,975 67 140274101647104 output_data.py:26] Writing out.json ..
[INFO deepomatic.cli.output_data 2019-05-27 09:52:19,975 67 140274101647104 output_data.py:28] Writing out.json done
[INFO deepomatic.cli.thread_base 2019-05-27 09:52:19,975 67 140274101647104 thread_base.py:180] Quitting OutputThread_0
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:52:46,967 67 140275327649536 client.py:127] Sending heartbeat
[INFO deepomatic.rpc.amqp.client 2019-05-27 09:53:16,970 67 140275327649536 client.py:127] Sending heartbeat
[ERROR deepomatic.cli.thread_base 2019-05-27 09:53:17,061 67 140275327649536 thread_base.py:73] list.remove(x): x not in list
[ERROR deepomatic.cli.thread_base 2019-05-27 09:53:17,062 67 140275327649536 thread_base.py:172] Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/workflow/rpc_workflow.py", line 37, in get_predictions
    response = self._consumer.get(self._correlation_id, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/rpc/amqp/entities.py", line 282, in get
    raise Timeout(timeout)
deepomatic.rpc.amqp.exceptions.Timeout: An AMQP timeout occured after 60 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/cmds/infer.py", line 177, in process_msg
    predictions = frame.inference_async_result.get_predictions(timeout=60)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/workflow/rpc_workflow.py", line 45, in get_predictions
    raise InferenceTimeout(timeout)
deepomatic.cli.workflow.workflow_abstraction.InferenceTimeout: timeout reached after 60

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/thread_base.py", line 170, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/thread_base.py", line 159, in _run
    msg_out = self.process_msg(msg_in)
  File "/usr/local/lib/python3.7/site-packages/deepomatic/cli/cmds/infer.py", line 196, in process_msg
    LOGGER.error("Couldn't get predictions for the whole batch in enough time ({} seconds). Ignoring frames {}.".format(e.timeout, self.batch))
AttributeError: 'ResultInferenceGreenlet' object has no attribute 'batch'

[INFO deepomatic.cli.thread_base 2019-05-27 09:53:17,062 67 140275327649536 thread_base.py:180] Quitting ResultInferenceGreenlet_0
```

So it's less severe than before: it doesn't seem to get indefinitely stuck anymore; but:
- the warm shutdown (1 SIGTERM) logs wrong timeouts values (and prints nested exceptions: bad UX)
- the hard shutdown (2 SIGTERM) effectively doesn't change anything vs warm shutdown

**Comment by maingoh** [comment]
How do you send those signals ? With a `Ctrl + C` ? KeyboardInterrupt raise a `SIGINT` not `SIGTERM`.

**Comment by thomas-riccardi** [comment]
Yes with `Ctrl+C`, but both SIGINT and SIGTERM are handled the same way:
https://github.com/Deepomatic/deepocli/blob/103ba48991ff446a0235f0ddb33c08957f001c1f/deepomatic/cli/thread_base.py#L288-L289

**Comment by maingoh** [comment]
Probably add a test for this as it is easy to break it (randomly send shutdown signal while deepocli is processing a video)
